### ISSUE TITLE
GPL license comments

### ISSUE THREAD

**Issue by rhennig** [henniggroup/MPInterfaces#2]
Hi Kiran,

We probably should add the GPL license comments into the source files. I could not find them in the files I looked at. Could you please take care of this.

Thanks,
Richard

**Comment by matk86** [comment]
Since materialsproject packages are distributed under MIT license and to avoid any possible compatibility issues, I have changed GPL to MIT. I have added the complete license statement to the README file and mentioned the license in the setup.py as well as the other module files in the mpinterfaces package.
